# Generated by Django 3.0.7 on 2021-02-12 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_staff', models.BooleanField(blank=True, null=True)),
                ('registration_id', models.CharField(help_text='Enter Registration Id', max_length=10)),
                ('enrollment_number', models.CharField(help_text='Enter Enrollment Number', max_length=10)),
                ('image', models.ImageField(blank=True, default='default.jpg', help_text='Upload Your Picture', null=True, upload_to='profiles_pics')),
                ('signature_image', models.ImageField(blank=True, help_text='Upload Your signature image', null=True, upload_to='sign_pics')),
                ('aadhar_image', models.ImageField(blank=True, help_text='Upload Adahar Id Picture', null=True, upload_to='aadhar_pics')),
                ('high_school_certificate_image', models.ImageField(blank=True, help_text='Upload High School Certificate Image', null=True, upload_to='highschool_certificate_pics')),
                ('intermediate_certificate_image', models.ImageField(blank=True, help_text='Upload Intermediate Certificate Image', null=True, upload_to='intermediate_certificate_pics')),
                ('college_certificate_image', models.ImageField(blank=True, help_text='Upload Previous College Certificate Image ** Passed Year Marksheet/ Transfer Certificate', null=True, upload_to='college_certificate_pics')),
                ('date_of_birth', models.DateField(help_text='Enter Date Of Birth ** Format - "dd/mm/yyyy"', null=True)),
                ('father_name', models.CharField(help_text='Enter Father Name', max_length=30)),
                ('mother_name', models.CharField(help_text='Enter Mother Name', max_length=30)),
                ('domicile', models.CharField(blank=True, choices=[('Uttarakhand', 'Uttarakhand'), ('Other State', 'Other State')], help_text='Choose Your Domicile', max_length=13, null=True)),
                ('aadhar', models.CharField(help_text='Enter Aadhar Id Number', max_length=17)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], help_text='Choose Your Gender', max_length=10, null=True)),
                ('religion', models.CharField(blank=True, choices=[('Indian', 'Indian')], help_text='Choose Your Religion', max_length=15, null=True)),
                ('category', models.CharField(blank=True, choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], help_text='Choose Category', max_length=15, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('Indian', 'Indian')], help_text='Proud To Say Indian', max_length=15, null=True)),
                ('department', models.CharField(blank=True, choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts'), ('BBA', 'BBA'), ('B.Ed', 'B.Ed'), ('M.Ed', 'M.Ed')], help_text='Choose Your Department', max_length=15, null=True)),
                ('course', models.CharField(blank=True, choices=[('B.Sc', 'B.Sc'), ('B.Com', 'B.Com'), ('B.A', 'B.A'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('B.Ed', 'B.Ed'), ('M.Ed', 'M.Ed'), ('M.Sc', 'M.Sc'), ('M.Com', 'M.Com'), ('M.A', 'M.A'), ('Course1', 'Course1'), ('Course2', 'Course2')], help_text='Choose Your Course', max_length=15, null=True)),
                ('subjects_1', models.CharField(blank=True, choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Zoology', 'Zoology'), ('Statics', 'Statics'), ('Maths', 'Maths'), ('English', 'English'), ('Hindi', 'Hindi'), ('Sanskrit', 'Sanskrit'), ('Sociology', 'Sociology')], help_text='Choose Your Subject 1', max_length=15, null=True)),
                ('subjects_2', models.CharField(blank=True, choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Zoology', 'Zoology'), ('Statics', 'Statics'), ('Maths', 'Maths'), ('English', 'English'), ('Hindi', 'Hindi'), ('Sanskrit', 'Sanskrit'), ('Sociology', 'Sociology')], help_text='Choose Your Subject 2', max_length=15, null=True)),
                ('subjects_3', models.CharField(blank=True, choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Zoology', 'Zoology'), ('Statics', 'Statics'), ('Maths', 'Maths'), ('English', 'English'), ('Hindi', 'Hindi'), ('Sanskrit', 'Sanskrit'), ('Sociology', 'Sociology')], help_text='Choose Your Subject 3', max_length=15, null=True)),
                ('subjects_4', models.CharField(blank=True, choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Zoology', 'Zoology'), ('Statics', 'Statics'), ('Maths', 'Maths'), ('English', 'English'), ('Hindi', 'Hindi'), ('Sanskrit', 'Sanskrit'), ('Sociology', 'Sociology')], help_text='Choose Your Subject 4 ** if you have ', max_length=15, null=True)),
                ('subjects_5', models.CharField(blank=True, choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Zoology', 'Zoology'), ('Statics', 'Statics'), ('Maths', 'Maths'), ('English', 'English'), ('Hindi', 'Hindi'), ('Sanskrit', 'Sanskrit'), ('Sociology', 'Sociology')], help_text='Choose Your Subject 5  ** if you have', max_length=15, null=True)),
                ('semester', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], help_text='Choose your Semester', max_length=3, null=True)),
                ('High_school_name', models.CharField(blank=True, help_text='Enter High School Name', max_length=50, null=True)),
                ('High_school_board', models.CharField(blank=True, help_text='Enter High School Board', max_length=50, null=True)),
                ('High_school_marks_obtained', models.IntegerField(blank=True, help_text='Enter High School Marks Obtained', null=True)),
                ('High_school_total_marks', models.IntegerField(blank=True, help_text='Enter High School Total Marks ', null=True)),
                ('High_school_percentage', models.FloatField(blank=True, help_text='Enter High School Percentage Obtained', null=True)),
                ('High_school_subject_1', models.CharField(blank=True, help_text='Enter High School Subject 1', max_length=10, null=True)),
                ('High_school_subject_2', models.CharField(blank=True, help_text='Enter High School Subject 2', max_length=10, null=True)),
                ('High_school_subject_3', models.CharField(blank=True, help_text='Enter High School Subject 3', max_length=10, null=True)),
                ('High_school_subject_4', models.CharField(blank=True, help_text='Enter High School Subject 4', max_length=10, null=True)),
                ('High_school_subject_5', models.CharField(blank=True, help_text='Enter High School Subject 5', max_length=10, null=True)),
                ('Intermediate_school_name', models.CharField(blank=True, help_text='Enter Intermediate School Name', max_length=50, null=True)),
                ('Intermediate_school_board', models.CharField(blank=True, help_text='Enter Intermediate School Board', max_length=50, null=True)),
                ('Intermediate_school_marks_obtained', models.IntegerField(blank=True, help_text='Enter Intermediate Makrs Obtained', null=True)),
                ('Intermediate_total_marks', models.IntegerField(blank=True, help_text='Enter Intermediate Total Marks', null=True)),
                ('Intermediate_school_percentage', models.FloatField(blank=True, help_text='Enter Intermediate Percentage', null=True)),
                ('Intermediate_school_subject_1', models.CharField(blank=True, help_text='Enter High School Subject 1', max_length=10, null=True)),
                ('Intermediate_school_subject_2', models.CharField(blank=True, help_text='Enter High School Subject 2', max_length=10, null=True)),
                ('Intermediate_school_subject_3', models.CharField(blank=True, help_text='Enter High School Subject 3', max_length=10, null=True)),
                ('Intermediate_school_subject_4', models.CharField(blank=True, help_text='Enter High School Subject 4', max_length=10, null=True)),
                ('Intermediate_school_subject_5', models.CharField(blank=True, help_text='Enter High School Subject 5', max_length=10, null=True)),
                ('College_name', models.CharField(blank=True, help_text='Enter Previous College Name', max_length=50, null=True)),
                ('College_board', models.CharField(blank=True, help_text='Enter University Name', max_length=50, null=True)),
                ('College_marks_obtained', models.IntegerField(blank=True, help_text='Makes Obtained in Last Exam', null=True)),
                ('total_marks', models.IntegerField(blank=True, help_text='Enter Total Marks', null=True)),
                ('percentage', models.FloatField(blank=True, help_text='Enter Percentage Obtained', null=True)),
                ('Course_name', models.CharField(blank=True, help_text='Enter Course you Enrolled', max_length=30, null=True)),
                ('Course_semester', models.IntegerField(blank=True, help_text='Enter Semester Your Passed', null=True)),
                ('mobile', models.CharField(blank=True, help_text='Enter Your Mobile number', max_length=10, null=True)),
                ('house_no', models.CharField(blank=True, help_text='Enter House / Flat Number / Colony / Ward No. ', max_length=20, null=True)),
                ('address', models.CharField(blank=True, help_text='Enter Your Address Details', max_length=20, null=True)),
                ('city', models.CharField(blank=True, help_text='Enter Your City', max_length=20, null=True)),
                ('state', models.CharField(blank=True, help_text='Enter Your State', max_length=20, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Enter Your Postal Code ** PIN Code', max_length=6, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB- ', 'AB-'), ('O+', 'O+'), ('O- ', 'O-')], help_text='Choose Your Blood Group', max_length=5, null=True)),
                ('skill', models.CharField(blank=True, help_text='About Your Skills - Things you do greatly', max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
